### ISSUE TITLE
Comparison to FLAnimatedImage

### ISSUE THREAD

**Issue by mitchellporter** [wangjwchn/AImage#1]
Hey @wangjwchn, thanks for open sourcing this! I was using `FLAnimatedImage` in a project several weeks ago and had to abandon GIF support because of the memory issues. Although in Xcode it would show never ending memory growth, I wasn't experiencing an actual memory leak, it was just that the caching system they had implemented was poor and was causing really high transient counts in Instruments.

I would love to run some tests and compare `JWAnimatedImage's` transient counts to `FLAnimatedImage's.`

**Comment by wangjwchn** [comment]
Hi @mitchellporter,thanks for your contribution to this repository.

**Comment by wangjwchn** [comment]
After reading your opinion of the high memory problem of FLAnimatedImage I did some tests,I think you are right about this,I will modify it later.

**Comment by mitchellporter** [comment]
I wish I could provide more info, but I abandoned the problem and didn't even fully understand the problem myself. A mentor with much more experience than me took a look at their code and told me they had created a crappy caching system when they should have been using `NSCache`.

He took a quick crack at replacing their caching system with `NSCache` and he had already solved a lot of the memory issues but I never got access to the code and he had other things to work on.

All I know for sure is that if you run `FLAnimatedImage` in instruments you will notice constant transient objects growth, which is a bad thing, and you probably don't want to ship an app with that type of behavior.

Hopefully your library can solve some of these issues :)

**Comment by wangjwchn** [comment]
My library is just completed, it will frequent update and may have some big changes. I optimized caching just now.If you take a long time for each measurement, I suggest you can wait about a week to avoid frequent measurement

**Comment by fboulegue** [comment]
Keep us updated please :-)! :+1:

**Comment by wangjwchn** [comment]
ok~~

**Comment by fboulegue** [comment]
Closed = fixed? @wangjwchn

**Comment by wangjwchn** [comment]
I think I've finished the main part of my library,You can benchmark now.
About FLAnimatedImage,I think that memory issue still exist.

**Comment by wangjwchn** [comment]
@mitchellporter

**Comment by wangjwchn** [comment]
Yes.There is no issues in this library now.@fboulegue

**Comment by mitchellporter** [comment]
@wangjwchn Congratulations, I just saw your updated Instruments result images! Is there any way you can share a sample project that you used to test 30 gifs at once? I'd love to have a test project to start with, and then I'll try and add in fetching the gifs from a remote source and I'll keep testing from there.

Thanks.

**Comment by wangjwchn** [comment]
I 've shared it in the example.@mitchellporter

**Comment by mitchellporter** [comment]
Thanks @wangjwchn and great work 👍
