### ISSUE TITLE
iOS10?

### ISSUE THREAD

**Issue by dhoerl** [wangjwchn/AImage#16]
Not really a code issue, really a documentation/README issue. Your README says this code hasn't been updated since April 2016 but of course it has. Also, FLAnimatedImage has had issues (or reported issues) with iOS 10. Have you tested with iOS10 yet? if you would just update the README you can then delete or close this issue.

Thanks for creating this repository!

**Comment by wangjwchn** [comment]
Hi,@dhoerl
I tried to updated this repository with swift 3 and tested on iPhone SE with Xcode 8 beta 2,but it seems that `CADisplayLink` has some problems on `frameInterval`.I 'm digging into that,trying to test repository with Xcode8 beta6.Hope to get good news.

**Comment by dhoerl** [comment]
I understand. In iOS9, we use slow GIFs and found that frameIntervals were a problem with the new hardware. Its quite a problem. Thank you for your response.

**Comment by wangjwchn** [comment]
@dhoerl 
Fixed in the [latest commit](https://github.com/wangjwchn/AImage/commit/5940cf90cf0be7a0c8959e92dae30ba3f59d1bd2).
