### ISSUE TITLE
IOS 10 EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by kleiberjp** [wangjwchn/AImage#17]
Have setted all parameter as Readme File specified, in the moment of excecution  at line 61 AImage.swift file occurs EXC_BAD_ACCESS trying check CFDictionaryContainsKey(imageProperties[1],unsafeAddressOf("{GIF}"))

**Comment by azureplus** [comment]
+1

**Comment by azureplus** [comment]
"{GIF}"->kCGImagePropertyGIFDictionary
"{PNG}"->kCGImagePropertyPNGDictionary

Test in iPhone6plus iOS 10 GM

**Comment by azureplus** [comment]
"{GIF}"->kCGImagePropertyGIFDictionary
"{PNG}"->kCGImagePropertyPNGDictionary

Test in iPhone6s plus iOS 10 GM

**Comment by jiaohaibin** [comment]
+1

**Comment by Dhruv8015** [comment]
Same Issue in ios 10 iphone 5s
Can anybody solve this?

**Comment by wangjwchn** [comment]
@kleiberjp @azureplus @jiaohaibin @Dhruv8015 
Fixed in the [latest commit](https://github.com/wangjwchn/AImage/commit/5940cf90cf0be7a0c8959e92dae30ba3f59d1bd2).
