### ISSUE TITLE
iOS10 kCGImagePropertyGIFDictionary or kCGImagePropertyPNGDictionary 

### ISSUE THREAD

**Issue by azureplus** [wangjwchn/AImage#18]
```
    var frameProperties = [CFDictionary]()
    if(imageProperty.imageType == ImageType.Gif){
        frameProperties = imageProperties.map(){
            let propertyGIFDic =  CFDictionaryGetValue($0,unsafeAddressOf(kCGImagePropertyGIFDictionary))
            return unsafeBitCast(propertyGIFDic,CFDictionary.self)
        }//gif
    }
    else if(CFDictionaryContainsKey(imageProperties[0],unsafeAddressOf(kCGImagePropertyPNGDictionary))){
        frameProperties = imageProperties.map(){
            unsafeBitCast(CFDictionaryGetValue($0,unsafeAddressOf(kCGImagePropertyPNGDictionary)),CFDictionary.self)
        }//apng
    }
```

**Comment by azureplus** [comment]
if(imageProperty.imageType == ImageType.Gif){
           imagePropertyDicKey = kCGImagePropertyGIFDictionary
        }else{
            imagePropertyDicKey = kCGImagePropertyPNGDictionary
        }
        frameProperties = imageProperties.map(){
            let propertyDic =  CFDictionaryGetValue($0,unsafeAddressOf(imagePropertyDicKey))
            return unsafeBitCast(propertyDic,CFDictionary.self)
        }

**Comment by wangjwchn** [comment]
@azureplus 
Fixed in the [latest commit](https://github.com/wangjwchn/AImage/commit/5940cf90cf0be7a0c8959e92dae30ba3f59d1bd2).Thanks for your advise!
