### ISSUE TITLE
fatal error: Index out of range

### ISSUE THREAD

**Issue by chanonly123** [wangjwchn/AImage#30]
![screen shot 2017-10-04 at 1 03 48 pm](https://user-images.githubusercontent.com/13619184/31164385-8ea16c36-a904-11e7-9152-dcc05f3c8f21.png)

**Comment by Alex601t** [comment]
@chanonly123 thx for you issue. This issue will be closed after merging PR https://github.com/wangjwchn/AImage/pull/33
