### ISSUE TITLE
 Unable to bridge NSNumber to Float

### ISSUE THREAD

**Issue by turk-jk** [wangjwchn/AImage#38]
I have know idea what I'm doing wrong but it's crashing since swift 4.1
` }
        
        let frameDelays: [Float] = frameProperties.map() {
            var delayObject: AnyObject = unsafeBitCast(CFDictionaryGetValue($0, Unmanaged.passUnretained(kCGImagePropertyGIFUnclampedDelayTime).toOpaque()), to: AnyObject.self)
            if (delayObject.floatValue == 0.0){
                delayObject = unsafeBitCast(CFDictionaryGetValue($0, Unmanaged.passUnretained(kCGImagePropertyGIFDelayTime).toOpaque()), to: AnyObject.self)
            }
            return delayObject as! Float   // <-- error occurs here
        }
        return frameDelays
    }`

**Comment by sarrathy** [comment]
Same issue for me too
For now i hard coded it . 
 if let probability = delayObject as? Float{
                return probability
            }
   return 0.1

**Comment by BeckWang0912** [comment]
I suggest this 
` if let n = delayObject as? NSNumber {
          return n.floatValue
  }`

**Comment by proxpero** [comment]
I fixed this with 
`return delayObject.floatValue as Float`

ie. get the scalar float value out of the NSNumber object before trying to bridge. It should always succeed.
