### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by TofPlay** [wangjwchn/AImage#4]
It's will be great to add [Carthage](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started) support
You can follow this tutorial: [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)

**Comment by wangjwchn** [comment]
I'll try.

**Comment by wangjwchn** [comment]
I think it's working now.@TofPlay

**Comment by TofPlay** [comment]
@wangjwchn I tested. Work like a charm 👍🙂
