### ISSUE TITLE
Framerate increasing in a reuse context

### ISSUE THREAD

**Issue by alexiscreuzot** [wangjwchn/AImage#6]
When using GIFs on a `UICollectionView` cell that is reused, the framerate does increase exponentially. A great addition would be to set a maximum framerate.

**Comment by wangjwchn** [comment]
Hi,@kirualex
I fixed this issue in a different way. Because I think your method may have repetitive calculation or generation when UICollectionView is resued.You can see it at latest release(0.1.3).

**Comment by alexiscreuzot** [comment]
:+1:
